### ISSUE TITLE
Error Creating Reccuring Event

### ISSUE THREAD

**Issue by Fummowo** [null404org/discord_google_calendar_bot#25]
I have a couple recurring events in the server I am attempting to add the bot to, it has managed to create 4 of the 9 events, however it is now seemingly getting stuck creating the next one. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/app/discord_google_calendar_bot.py", line 354, in on_ready
  File "/app/discord_google_calendar_bot.py", line 169, in create_google_event
    recurrence_rule = get_scheduled_event_recurrence_rule(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/discord_google_calendar_bot.py", line 112, in get_scheduled_event_recurrence_rule
    if event_data["recurrence_rule"] is not None:
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'recurrence_rule'
ERROR:discord.client:Ignoring exception in on_ready
    create_google_event(discord_event)
```

**Comment by warelock2** [comment]
@Fummowo Right-click your Discord server, copy the server ID, and paste it here. I'll take a look.
